### ISSUE TITLE
这个能把收费功能去掉吗？

### ISSUE THREAD

**Issue by sandu666** [Pings1031/cpmanghe#1]

**Comment by Pings1031** [comment]
自动回复：    您的申请已收到，将在72小时之内处理回复    更多介绍访问官网查看：https://team.bugfor.com    请添加QQ交流群：470391814

**Comment by BugFor-Pings** [comment]
可以去除的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Pings1031/cpmanghe"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月10日(星期一) 晚上7:59
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[Pings1031/cpmanghe] 这个能把收费功能去掉吗？ (Issue #1)

**Comment by sandu666** [comment]
大佬 能发一个去支付 直接能取放的玩玩吗

**Comment by Pings1031** [comment]
这个项目最初版就是为了能够有收入而开发的，并没用想过做成免费的，如果有需要，可以花钱定制一套免费的。




924984
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Pings1031/cpmanghe"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月14日(星期五) 下午3:47
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Pings1031/cpmanghe] 这个能把收费功能去掉吗？ (Issue #1)





 
大佬 能发一个去支付 直接能取放的玩玩吗

**Comment by BugFor-Pings** [comment]
这个本身就是为了有收入而开发的，如果你需要免费的，得需要自己花点时间改
